# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build Regal
        run: |
          cd build/ios/Regal
          xcodebuild
          wget https://github.com/kakashidinho/metalangle/releases/download/gles3-0.0.7/MetalANGLE.framework.ios.zip
          unzip MetalANGLE.framework.ios.zip
          clang++ -dynamiclib -fPIC -arch arm64 -isysroot /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=12.0 -F. -framework MetalANGLE -o libRegal.dylib -Wl,-all_load build/Release-iphoneos/libRegal.a

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: libRegal
          path: build/ios/Regal/libRegal.dylib
